Repository e2b-dev/desktop, pull requests merged in 2025-05, with the labels that each got.

#79 Desktop SDK: set global DISPLAY env variable
  .changeset/lucky-eyes-end.md
  packages/js-sdk/src/sandbox.ts
  packages/python-sdk/e2b_desktop/main.py
Labels: python, javascript

#83 Added desktop.launch method to launch GUI applications
  .changeset/witty-buttons-smell.md
  README.md
  packages/js-sdk/README.md
  packages/js-sdk/src/sandbox.ts
  packages/python-sdk/README.md
  packages/python-sdk/e2b_desktop/main.py
  template/e2b.Dockerfile
Labels: enhancement

#86 Updated readme with example use-case
  .changeset/fruity-zoos-try.md
  README.md
  examples/streaming-apps-javascript/README.md
  examples/streaming-apps-python/README.md
  packages/js-sdk/README.md
  packages/js-sdk/src/sandbox.ts
  packages/python-sdk/README.md
  packages/python-sdk/e2b_desktop/main.py
Labels: documentation

#90 Added screenshots to the streaming examples readmes
  examples/readme-assets/chrome.png
  examples/readme-assets/vscode.png
  examples/streaming-apps-javascript/README.md
  examples/streaming-apps-python/README.md
Labels: documentation

#87 Make Firefox the default browser for opening links
  template/e2b.Dockerfile
Labels: enhancement

#95 Fix dependencies
  packages/js-sdk/package-lock.json
  pnpm-lock.yaml
Labels: dependencies

#100 Fixes restarting desktop environment when trying to reconnect
  .changeset/clean-mugs-say.md
  packages/python-sdk/e2b_desktop/main.py
Labels: enhancement
