Repository e2b-dev/desktop, pull requests merged in 2025-04, with the labels that each got.

#54 Update Ubuntu base image to 22.04
  .github/workflows/publish_packages.yml
  .github/workflows/template.yml
Labels: dependencies

#55 Show SDK ref dir only when it exists in GH publish workflow
  .github/workflows/publish_packages.yml
Labels: bug

#56 Organize and simplify Dockerfile
  template/45-allow-colord.pkla
  template/Xauthority
  template/e2b.Dockerfile
  template/requirements.txt
  template/settings.json
Labels: enhancement

#58 Remove arm64 from template build pipeline
  .github/workflows/template.yml
Labels: bug

#57 Set desktop background using custom sandbox template
  packages/js-sdk/src/sandbox.ts
  packages/python-sdk/e2b_desktop/main.py
  template/e2b.Dockerfile
  template/xfce4-desktop.xml
Labels: enhancement

#59 Add view_only and resize to getURL
  .changeset/great-eyes-double.md
  README.md
  packages/js-sdk/src/sandbox.ts
  packages/python-sdk/e2b_desktop/main.py
  packages/python-sdk/example.py
Labels: enhancement

#63 Set timeout for background processes to infinity
  .changeset/neat-trams-draw.md
  packages/js-sdk/src/sandbox.ts
  packages/python-sdk/e2b_desktop/main.py
Labels: bug

#64 Remove first start firefox screen + general improvements for firefox
  template/e2b.Dockerfile
  template/firefox-autoconfig.js
  template/firefox-policies.json
  template/firefox.cfg
Labels: enhancement

#65 No autoupdate for firefox
  template/firefox.cfg
Labels: enhancement

#66 Add SDK tests to PRs
  .github/workflows/js_sdk_tests.yml
  .github/workflows/python_sdk_tests.yml
  packages/js-sdk/tests/mouse.test.ts
  packages/python-sdk/e2b_desktop/main.py
  packages/python-sdk/tests/test_controls.py
Labels: enhancement

#68 Remove filtering to make it possible to require the chekcs
  .github/workflows/js-sdk-tests.yml
  .github/workflows/pull-request.yml
  .github/workflows/python-sdk-tests.yml
Labels: enhancement

#69 Pass secrets correctly to workflows
  .github/workflows/js-sdk-tests.yml
  .github/workflows/pull-request.yml
  .github/workflows/python-sdk-tests.yml
Labels: bug

#70 Security patches
  package-lock.json
  package.json
  packages/python-sdk/poetry.lock
  pnpm-lock.yaml
Labels: dependencies

#80 Update JS SDK target to es2017
  .changeset/happy-plants-start.md
  packages/js-sdk/tsup.config.js
Labels: javascript
